config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tag/index'

  get 'user/index'

  get 'image/show'

  get 'image_gallery/index'

  root 'home#index'

  resources :images, :image_galleries

end

app/models/concerns/randomable.rb
module Randomable
  extend ActiveSupport::Concern

  class_methods do
    def random(the_count = 1)
      records = offset(rand(count - the_count)).limit(the_count)
      the_count == 1 ? records.first : records
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :image_gallery
  belongs_to :user

  validates :name, presence: true, uniqueness: true
  validates :image_gallery, presence: true

  attachment :image

  acts_as_taggable # Alias for acts_as_taggable_on :tags

end

app/models/image_gallery.rb
class ImageGallery < ActiveRecord::Base
  attachment :image, type: :image

  validates_presence_of :title

  has_many :images, dependent: :destroy
  belongs_to :user
  
  accepts_attachments_for :images
end

app/models/tag.rb
has_many :taggings
has_many :articles, through: :taggings

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
  has_many :image_galleries, through: :images

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/image_galleries_controller.rb
class ImageGalleriesController < ApplicationController
  def index
    @image_gallery = ImageGallery.all
  end

  def new
    @image_gallery = ImageGallery.new
  end

  def show
    @image_gallery = ImageGallery.find(params[:id])
  end

  def create
    @image_gallery = ImageGallery.new(image_gallery_params)
    if @image_gallery.save
      redirect_to @image_gallery
    else
      render :new
    end
  end

  def edit
    @image_gallery = ImageGallery.find(params[:id])
  end

  def update
    @image_gallery = ImageGallery.find(params[:id])
    if @image_gallery.update_attributes(image_gallery_params)
      redirect_to @image_gallery
    else
      render :new
    end
  end

  def destroy
    @image_gallery = ImageGallery.find(params[:id])
    @image_gallery.destroy
    redirect_to :image_galleries
  end

private

  def image_gallery_params
    params.require(:image_gallery).permit(:title, :image, :body, images: [])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # def image_params
  #   params.require(:image).permit(:name, :tag_list) ## Rails 4 strong params usage
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
  def field_errors(object, column)
    errors = object.errors[column]
    if errors.present?
      content_tag(:p, errors.to_sentence, class: "field-error")
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_gallery_helper.rb
module ImageGalleryHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.slim
= title "Photo Galleries"

h1 Photo Galleries

app/views/image_galleries/_form.html.slim
.row
  .col-md-8
    = form_for @image_gallery do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: "form-control"
        = field_errors(@image_gallery, :title)
      .form-group
        = f.label :image
        p
          = attachment_image_tag @image, :image, :fill, 60, 60
          = f.attachment_field :image
        = field_errors(@image_gallery, :image)
      .form-group
        = f.label :images_files, "Images"
        = f.attachment_field :image, multiple: true
        = field_errors(@image_gallery, :images_files)
      .form-group
        = f.label :body
        = f.text_area :body, class: "form-control"
        = field_errors(@image_gallery, :body)
      .form-group
        = f.submit class: "btn btn-primary"
  .col-md-4

app/views/image_galleries/edit.html.slim
h1 Edit image gallery

= render "form"

app/views/image_galleries/index.html.slim
h1 Image Galleries

p = link_to "New gallery", :new_image_gallery, class: "btn btn-primary", role: "button"

ul
  = @image_gallery.each do |g|
    li = link_to g.title, g

app/views/image_galleries/new.html.slim
h1 New image gallery

= render "form"

app/views/image_galleries/show.html.slim
h1 = @image_gallery.title

p 
  = link_to "Edit gallery", [:edit, @image_gallery], class: "btn btn-primary"
  = link_to "Delete gallery", @image_gallery, data: { method: "delete", confirm: "Are you sure?" }, class: "btn btn-danger"

= @image_gallery.images.each do |i|
  p
    = attachment_image_tag(@image_gallery, :image, :fill, 200, 200)
    = link_to image.image_filename, attachment_url(image, :file)
    = image.image_content_type
    = number_to_human_size image.image_size
    = simple_format @image_gallery.body

app/views/images/_form.html.slim
.field
  = f.label :tag_list, "Tags (separated by commas)" 
  br
  = f.text_field :tag_list

app/views/images/create.html.slim
h1 create image

app/views/images/index.html.slim
h1 Images

/ = image_tag attachment_url(@user, :profile_image, :fill, 300, 300, format: "jpg")

app/views/images/new.html.slim
/ = simple_form_for @image, url: images_path do |form|
/   = form.input :image_upload, as: :file

h1 Upload image

/ = form_for @image do |f|
/   = render 'shared/errors', object: @image_upload

/   = f.attachment_field :image_upload

/   / .form-group
/   /   = f.label :title
/   /   = f.text_field :title, class: 'form-control'

/   / .form-group
/   /   = f.label :image
/   /   = f.file_field :image, class: 'form-control'

/   = f.submit 'Upload', class: 'btn btn-primary'

app/views/images/show.html.slim
h1 Image#show

/ = image_tag attachment_url(@image, :image_upload, :fill, 300, 300, format: "jpg")

app/views/layouts/_footer.html.slim
p Footer

app/views/layouts/_header.html.slim
h1 Header
.pull-right
  = link_to "Home", root_path
  = link_to "Image galleries", :image_galleries
  = link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  .alert 
    a.close[data-dismiss="alert" href="#"] ×
    ul
      li
        = value

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for?(:title) ? content_for(:title) : "Photo Gallery App"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render partial: 'layouts/header'
    .container
      = render partial: 'layouts/messages'
      = yield
      = render partial: 'layouts/footer'

app/views/shared/_errors.html.slim
= if object.errors.any?
  .panel.panel-warning.errors
    .panel-heading
      h5
        i.glyphicon.glyphicon-exclamation-sign
        | Found errors while saving

    ul.panel-body
      = object.errors.full_messages.each do |msg|
        li = msg

app/views/users/index.html.slim
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>